language: python

sudo: false
dist: trusty

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install tox

script:
  - "tox -e ${TRAVIS_PYTHON_VERSION/[0-9].[0-9]/py${TRAVIS_PYTHON_VERSION/.}} -- --verbose"
